RefugieBundle\Entity\Refugie:
    type: entity
    table: null
    repositoryClass: RefugieBundle\Repository\RefugieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        age:
            type: string
            length: 255
        origine:
            type: string
            length: 255
    lifecycleCallbacks: {  }
