<?php

namespace RefugieBundle\Repository;

/**
 * RefugieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugieRepository extends \Doctrine\ORM\EntityRepository
{
}
